version: v1
plugins:
  - remote: buf.build/grpc-ecosystem/plugins/openapiv2:v2.7.3-1
    out: ../tmp-swagger-gen/spec.json
    # opt: 
      # - openapiv2_opt=./tmp-swagger-gen,logtostderr=true 
      # - swagger_opt=fqn_for_swagger_name=true 
      # - swagger_opt=simple_operation_ids=true
